version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: taskpilot_app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://admin:admin1234@postgres:5432/db_task_pilot
      - REDIS_URL=redis://cacher:6379
    env_file:
      - .env
    depends_on:
      - postgres
      - cacher
    restart: unless-stopped
    volumes:
      - ./app:/app/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  postgres:
    image: postgres:16.2
    container_name: postgres_task_pilot
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin1234
      POSTGRES_DB: db_task_pilot
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  cacher:
    image: redis:7.2.4-alpine
    container_name: redis_task_pilot
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  pgdata: